services:
  - type: web
    name: joinvagas-pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app_v2.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0